language: rust
dist: trusty
rust:
    - nightly
sudo: required
addons:
  apt:
    packages:
        - libpcap-dev
        - musl-tools
        - musl-dev
        - musl
script:
  - |
      # uninstall the rust toolchain installed by travis, we are going to use rustup
      sh ~/rust/lib/rustlib/uninstall.sh &&
      export PATH=$PATH:$HOME/.cargo/bin/ &&
      echo "Building static binary" &&
      sh extra/musl-build.sh &&
      echo "Building normal binary" &&
      CFLAGS="-I${PWD}/netmap/sys/" cargo build --verbose --target=`arch`-unknown-linux-gnu --release
