[package]
name = "syncookied"
version = "0.1.8"
description = "syn flood protection system"
authors = ["Alexander Polyakov <apolyakov@beget.ru>"]
build = "build.rs"
license = "GPL-2.0"
readme = "README.md"

[dependencies]
libc = "0.2.11"
crossbeam = "0.2.5"
clap = "2.4.0"
lazy_static = "0.2.1"
yaml-rust = "0.3.2"
parking_lot = "0.2.6"
fnv = "1.0.2"
chan-signal = "0.1.6"
log = "0.3.6"
syslog = "3.1.0"
chrono = "0.2.22"

[dependencies.influent]
git = "https://github.com/polachok/influent.rs"
branch = "udp+"
rev = "a2173c040baf099ec88ac47d8b2604868346cc23"
default-features = false
features = []

[dependencies.bpfjit]
git = "https://github.com/polachok/bpfjit"
rev = "2debf393d2cb1d7e0a8f9c2d3bb3cedcc17f2c76"

[dependencies.pcap]
git = "https://github.com/polachok/pcap"
rev = "f5bff0b0b18b7054ea3e84db00ccf4787dc5bb4c"
branch = "offline-bpf"

[dependencies.scheduler]
git = "https://github.com/polachok/rust-scheduler"
rev = "53b832905bf61ab8e8513e1fd9341a65d850ef27"
branch = "newer-libc"

[dependencies.bounded-spsc-queue]
git = "https://github.com/polachok/bounded-spsc-queue.git"
rev = "b6e0c6e4a93ba0db0c1579b4bc59f49392cab288"
branch = "with"

[dependencies.mpsc]
git = "https://github.com/polachok/mpsc.git"
rev = "bf5974342d20df47963fb5041c7f01157fbf441c"

[dependencies.netmap_sys]
git = "https://github.com/polachok/netmap_sys"
rev = "0d48d654fc4b1d8c29e33094afb29c11d4ce7c53"
features = [ "netmap_with_libs" ]

[dependencies.pnet]
git = "https://github.com/polachok/libpnet"
rev = "1e55befffd630cef33209396d629efc87fe8c74f"
branch = "syncookied"

[dependencies.intmap]
git = "https://github.com/polachok/intmap"
rev = "37c7289c1ecb7af4d28b66b041c81079f9dbdc3e"

[build-dependencies]
gcc = "0.3.26"

[profile.release]
debug = true
