[package]
name = "syncookied"
version = "0.1.9"
description = "syn flood protection system"
authors = ["Alexander Polyakov <apolyakov@beget.ru>"]
build = "build.rs"
license = "GPL-2.0"
readme = "README.md"

[dependencies]
libc = "0.2.11"
crossbeam = "0.2.5"
clap = "2.4.0"
lazy_static = "0.2.1"
yaml-rust = "0.3.2"
parking_lot = "0.2.6"
fnv = "1.0.2"
chan-signal = "0.1.6"
log = "0.3.6"
syslog = "3.1.0"
chrono = "0.2.22"

[dependencies.concurrent-hash-map]
git = "https://github.com/polachok/concurrent-hash-map"
branch = "hasher"
rev = "7a36b53b7d19755a34bf27d0ff6cde68d1e9af1d"

[dependencies.influent]
git = "https://github.com/polachok/influent.rs"
branch = "udp+"
rev = "c56247afeb2d7aac7dc0b6365aa89026f46ff5c7"
default-features = false
features = []

[dependencies.bpfjit]
git = "https://github.com/polachok/bpfjit"
rev = "2debf393d2cb1d7e0a8f9c2d3bb3cedcc17f2c76"

[dependencies.pcap]
git = "https://github.com/polachok/pcap"
rev = "f5bff0b0b18b7054ea3e84db00ccf4787dc5bb4c"
branch = "offline-bpf"

[dependencies.scheduler]
git = "https://github.com/polachok/rust-scheduler"
rev = "53b832905bf61ab8e8513e1fd9341a65d850ef27"
branch = "newer-libc"

[dependencies.bounded-spsc-queue]
git = "https://github.com/polachok/bounded-spsc-queue.git"
rev = "b6e0c6e4a93ba0db0c1579b4bc59f49392cab288"
branch = "with"

[dependencies.mpsc]
git = "https://github.com/polachok/mpsc.git"
rev = "bf5974342d20df47963fb5041c7f01157fbf441c"

[dependencies.netmap_sys]
git = "https://github.com/polachok/netmap_sys"
rev = "0d48d654fc4b1d8c29e33094afb29c11d4ce7c53"
features = [ "netmap_with_libs" ]

[dependencies.pnet]
git = "https://github.com/polachok/libpnet"
rev = "8eeb66788c2cd71228b15a80e8ae894ed56b4510"
branch = "syncookied"

[dependencies.intmap]
git = "https://github.com/polachok/intmap"
rev = "57eb64370d0400ceafce1d6c154375ff1cda83d1"

[build-dependencies]
gcc = "0.3.26"

[profile.release]
debug = true
