[package]
name = "syncookied"
version = "0.1.0"
authors = ["Alexander Polyakov <apolyakov@beget.ru>"]
build = "build.rs"

[dependencies]
libc = "0.2"
crossbeam = "0.2.5"
scheduler = "0.1.1"
clap = "2.4.0"

[dependencies.netmap_sys]
git = "https://github.com/libpnet/netmap_sys"
rev = "4bc5496c0afb6dc884a3d8c686a58bff82b323b8"
features = [ "netmap_with_libs" ]

[dependencies.pnet]
git = "https://github.com/libpnet/libpnet"
rev = "bdf864944dbc285db47978965fed6ea2076efc40"

[build-dependencies]
gcc = "0.3.26"

[profile.release]
debug = true
