[package]
name = "syncookied"
version = "0.1.0"
authors = ["Alexander Polyakov <apolyakov@beget.ru>"]
build = "build.rs"

[dependencies]
libc = "0.2"
crossbeam = "0.2.5"
scheduler = "0.1.1"
clap = "2.4.0"
lazy_static = "0.2.1"
yaml-rust = "0.3.2"
parking_lot = "0.2.6"
fnv = "1.0.2"
byteorder = "0.5.2"

[dependencies.bounded-spsc-queue]
git = "https://github.com/polachok/bounded-spsc-queue.git"
rev = "b6e0c6e4a93ba0db0c1579b4bc59f49392cab288"
branch = "with"

[dependencies.mpsc]
git = "https://github.com/polachok/mpsc.git"
rev = "bf5974342d20df47963fb5041c7f01157fbf441c"

[dependencies.netmap_sys]
git = "https://github.com/polachok/netmap_sys"
rev = "0d48d654fc4b1d8c29e33094afb29c11d4ce7c53"
features = [ "netmap_with_libs" ]

[dependencies.pnet]
git = "https://github.com/polachok/libpnet"
rev = "1e55befffd630cef33209396d629efc87fe8c74f"
branch = "syncookied"

[dependencies.intmap]
git = "https://github.com/polachok/intmap"
rev = "37c7289c1ecb7af4d28b66b041c81079f9dbdc3e"

[build-dependencies]
gcc = "0.3.26"

[profile.release]
debug = true
