[package]
name = "syncookied"
version = "0.1.0"
authors = ["Alexander Polyakov <apolyakov@beget.ru>"]
build = "build.rs"

[dependencies]
libc = "0.2"
crossbeam = "0.2.5"
scheduler = "0.1.1"
clap = "2.4.0"
lazy_static = "0.2.1"
yaml-rust = "0.3.2"
parking_lot = "0.1.2"

[dependencies.mpsc]
git = "https://github.com/polachok/mpsc.git"
rev = "bf5974342d20df47963fb5041c7f01157fbf441c"

[dependencies.netmap_sys]
git = "https://github.com/libpnet/netmap_sys"
rev = "4bc5496c0afb6dc884a3d8c686a58bff82b323b8"
features = [ "netmap_with_libs" ]

[dependencies.pnet]
git = "https://github.com/polachok/libpnet"
rev = "1e55befffd630cef33209396d629efc87fe8c74f"
branch = "syncookied"

[build-dependencies]
gcc = "0.3.26"

[profile.release]
debug = true
